lutaml/lutaml-model

lib/lutaml/model/xml_adapter/nokogiri_adapter.rb, spec/lutaml/model/xml_mapping_spec.rb
`p` is a private method in `Object` class, it was getting used when using `send` in [nokogiri_adaptar.rb:55](https://github.com/lutaml/lutaml-model/blob/main/lib/lutaml/model/xml_adapter/nokogiri_adapter.rb#L55) and instead of adding a `p` tag to `output xml` it was just printing the parameters.
Converted that to `public_send` and added a test case for that.
=> fix: issue with p tag in xml

README.adoc, lib/lutaml/model/attribute.rb, lib/lutaml/model/serialize.rb, lib/lutaml/model/xml_adapter/builder/nokogiri.rb, lib/lutaml/model/xml_adapter/builder/ox.rb, lib/lutaml/model/xml_adapter/nokogiri_adapter.rb, lib/lutaml/model/xml_adapter/ox_adapter.rb, lib/lutaml/model/xml_adapter/xml_document.rb, lib/lutaml/model/yaml_adapter/standard_yaml_adapter.rb, spec/fixtures/person.rb, spec/lutaml/model/custom_serialization_spec.rb, spec/lutaml/model/yaml_adapter_spec.rb
Now we are using models in between conversions instead of the intermediary hash.
For #51
=> feat: using model instead of hash in conversion

README.adoc
Fix `name_to_json` and `name_from_json` examples in readme.
fixes #66
=> fix: (to | from)_json example in readme

lib/lutaml/model/mapping_rule.rb, lib/lutaml/model/serialize.rb, lib/lutaml/model/utils.rb, lib/lutaml/model/xml_adapter/nokogiri_adapter.rb, lib/lutaml/model/xml_adapter/xml_document.rb, spec/lutaml/model/custom_model_spec.rb, spec/lutaml/model/serializable_spec.rb
Fixing issue when using `delegate` option with custom models.
fix #57
=> fix: delegate issue for text element in xml

README.adoc
As mentioned by @andrew2net here -> https://github.com/lutaml/lutaml-model/issues/83#issuecomment-2365239781. There is no example for custom methods for XML so this PR added the examples for XML in documentation.
=> Added example for `with` option for xml

lib/lutaml/model/serialize.rb, spec/lutaml/model/delegation_spec.rb, spec/lutaml/model/inheritance_spec.rb, spec/lutaml/model/serializable_spec.rb
Do not override parent mappings when inheriting.
Required for -> https://github.com/metanorma/rfcxml/pull/3
=> do not override parent mapping when inheriting

lib/lutaml/model/xml_adapter/builder/nokogiri.rb, lib/lutaml/model/xml_adapter/nokogiri_adapter.rb, lib/lutaml/model/xml_adapter/xml_document.rb, spec/lutaml/model/xml_mapping_spec.rb
`p` tags were being skipped because we were using `send` and instead of adding a `<p>` tag it was calling the private `p` method of the ruby `Object` class which is used to print to the console.
Updated the code to use `public_send` so this issue should be resolved now.
fix #99 
fix #102
=> fix: raw not keeping p tags

lib/lutaml/model/serialize.rb, lib/lutaml/model/xml_adapter/nokogiri_adapter.rb, lib/lutaml/model/xml_adapter/ox_adapter.rb, lib/lutaml/model/xml_mapping.rb, spec/lutaml/model/ordered_content_spec.rb
Added option `ordered: true` in root for only ordering the tags.
as discussed here -> https://github.com/lutaml/metaschema/issues/6#issuecomment-2426064137
=> feat: add ordered: true option

lib/lutaml/model/xml_adapter/xml_document.rb, spec/lutaml/model/xml_mapping_spec.rb
Fixed `schemaLocation` for models with `mixed: true`. 
For -> https://github.com/lutaml/metaschema/issues/7
=> fix: schema location for mixed content

lib/lutaml/model/xml_adapter/nokogiri_adapter.rb
Fix https://github.com/lutaml/lutaml-model/issues/127
=> Avoid invoking Nokogiri builder method when adding tags

lib/lutaml/model/xml_adapter/ox_adapter.rb, spec/lutaml/model/xml_adapter/ox_adapter_spec.rb
This PR fixes a crash while parsing a comment using the **Ox** parser.
=> Fix of the error while parsing comment with Ox adapter

lib/lutaml/model/xml_adapter/nokogiri_adapter.rb, spec/lutaml/model/xml_mapping_spec.rb
Default namespace was being applied even if it was not defined on the root element. 
fix #147
=> fix: from_xml not working for without namespaced elements

lib/lutaml/model/attribute.rb, lib/lutaml/model/serialize.rb, lib/lutaml/model/xml_mapping_rule.rb, spec/lutaml/model/namespace_spec.rb
@Novtopro @ronaldtse I faced a similar issue as mentioned here => https://github.com/lutaml/oasis-etm/issues/1#issuecomment-2454104356, while integrating **lutaml/lutaml-model** in plurimath/mml#2.
Opened this PR after discussing with @HassanAkbar.
@Novtopro let me know if this helps in your case.
=> Parent namespace for XML mapping

README.adoc, lib/lutaml/model/xml_adapter/nokogiri_adapter.rb, lib/lutaml/model/xml_adapter/ox_adapter.rb, spec/lutaml/model/delegation_spec.rb, spec/lutaml/model/mixed_content_spec.rb
Added Support for Encoding Options
Options:  
- `encoding: nil` (adapter uses its default encoding)
- `encoding: “encoding_name”`  
Default encoding is `UTF-8.` 
Note: if the encoding name is invalid, Nokogiri raises an error, while Ox defaults to its internal encoding.
The previous `encoding: true` option has been updated to accept `encoding: "encoding_name"`. 
resolves #163
=> feat: added support for encoding options

lib/lutaml/model/xml_adapter/xml_document.rb, spec/lutaml/model/xml_mapping_spec.rb
Fixes the issue when a prefix is not being added to the XML when passed explicitly when mapping an element.
fixes #152
=> prefix not added when defined explicitly

lib/lutaml/model/json_adapter/json_document.rb, lib/lutaml/model/json_adapter/multi_json_adapter.rb, lib/lutaml/model/json_adapter/standard_json_adapter.rb, lib/lutaml/model/serialize.rb, lib/lutaml/model/toml_adapter/toml_document.rb, lib/lutaml/model/toml_adapter/toml_rb_adapter.rb, lib/lutaml/model/toml_adapter/tomlib_adapter.rb, lib/lutaml/model/xml_adapter/nokogiri_adapter.rb, lib/lutaml/model/xml_adapter/oga_adapter.rb, lib/lutaml/model/xml_adapter/ox_adapter.rb, lib/lutaml/model/xml_adapter/xml_document.rb, lib/lutaml/model/yaml_adapter/standard_yaml_adapter.rb, lib/lutaml/model/yaml_adapter/yaml_document.rb, spec/fixtures/xml/latin_encoding.xml, spec/fixtures/xml/shift_jis.xml, spec/lutaml/model/mixed_content_spec.rb
Support Encoding in Parsing
resolves #188
=> feat: support encoding in parsing

lib/lutaml/model/serialize.rb, spec/lutaml/model/custom_serialization_spec.rb
This PR fixes the attribute from being fetched when no `to:` parameter is given in the mapping in case of missing attributes. It tries to fetch the attribute and returns `nil,` which breaks the code in the case of custom methods.
Added specs to ensure that the model instance is correctly instantiated in case of missing attributes as well.
Fixes -> [#211](https://github.com/lutaml/lutaml-model/issues/211)
=> Fix key value requires "to:" with custom methods

README.adoc, lib/lutaml/model/attribute.rb, lib/lutaml/model/serialize.rb, lib/lutaml/model/type/time.rb, lib/lutaml/model/utils.rb, lib/lutaml/model/validation.rb, spec/lutaml/model/custom_serialization_spec.rb, spec/lutaml/model/enum_spec.rb, spec/lutaml/model/render_nil_spec.rb
Add enum methods to serializable
fixes #201
=> feat: adding enum methods to serializeable

lib/lutaml/model/type/decimal.rb, spec/fixtures/sample_model.rb, spec/sample_model_spec.rb
Fix decimal serialization to YAML returns ruby object instead of value
fixes [#206](https://github.com/lutaml/lutaml-model/issues/206)
=> fix decimal attribute serializing to ruby object in YAML

lib/lutaml/model/serialize.rb, spec/lutaml/model/included_spec.rb, spec/lutaml/model/serializable_spec.rb
This PR fixes the error when `Lutaml::Model::Serialize` module is `included` instead of `inherited` in a model.
This error resulted from instance variables, such as `@attributes`, not being set in the `def included `method just as they were set in the `def inherited` method.
So, I created a common function for both and called it according to both implementations written in the documentation for using the gem.
Fixes: [#203 ](https://github.com/lutaml/lutaml-model/issues/203)
=> Fix error when serialize module is included

lib/lutaml/model/xml_adapter/xml_document.rb, spec/lutaml/model/custom_model_spec.rb
This PR fixes an issue with `map_content` when a separate model is used and custom methods are used with it.
Also added specs to ensure it doesn't break in the future.
fixes [#200](https://github.com/lutaml/lutaml-model/issues/200)
=> Fix error with custom methods and separate model

lib/lutaml/model/serialize.rb, spec/address_spec.rb, spec/lutaml/model/type/boolean_spec.rb
This happened because `||` was used to check whether the value existed, and `false` caused it to think that the value did not exist.
fixes #225
=> boolean false breaking

lib/lutaml/model/serialize.rb, spec/lutaml/model/render_nil_spec.rb
The issue occurred because we checked for the nil value before converting the instance to the specified format.
fixes #226
=> render nil not working for empty object

README.adoc, lib/lutaml/model/xml_adapter/builder/oga.rb, lib/lutaml/model/xml_adapter/oga/document.rb, lib/lutaml/model/xml_adapter/oga/element.rb, lib/lutaml/model/xml_adapter/oga_adapter.rb, lib/lutaml/model/xml_adapter/xml_document.rb, spec/lutaml/model/mixed_content_spec.rb, spec/lutaml/model/ordered_content_spec.rb, spec/lutaml/model/xml_adapter/oga_adapter_spec.rb, spec/lutaml/model/xml_adapter/xml_namespace_spec.rb, spec/lutaml/model/xml_adapter_spec.rb, spec/lutaml/model/xml_mapping_spec.rb
This PR supports the **Oga** adapter for **XML** serialization.
=> Oga adapter support

lib/lutaml/model.rb, lib/lutaml/model/attribute.rb, lib/lutaml/model/loggable.rb, lib/lutaml/model/xml_adapter/xml_document.rb, lib/lutaml/model/xml_mapping.rb, spec/lutaml/model/xml_mapping_spec.rb
Warn the user about the automatic handling of `schemaLocation` and use the user-defined attribute if present.
closes #232 
closes #239
=> warn user about automatic handling of schemaLocation

lib/lutaml/model/xml_adapter/xml_document.rb, spec/lutaml/model/custom_model_spec.rb, spec/lutaml/model/mixed_content_spec.rb
This PR adds fix for the unescaping of characters such as `<` and `>` when using `raw: true` option with attribute.
fixes #241
=> raw true option should keep strings unescaped in to_xml output

lib/lutaml/model/mapping_hash.rb, lib/lutaml/model/serialize.rb, lib/lutaml/model/type/hash.rb, lib/lutaml/model/xml_adapter/xml_document.rb, lib/lutaml/model/xml_mapping_rule.rb, spec/lutaml/model/cdata_spec.rb, spec/lutaml/model/custom_model_spec.rb, spec/lutaml/model/xml_mapping_spec.rb
Resolves these issue by separating the `elements`, `attributes`, and `text` in `mapping_hash`
closes #231
closes #217
=> fix: same element and attribute name issue

lib/lutaml/model/xml_adapter/nokogiri_adapter.rb, spec/lutaml/model/xml_adapter/xml_namespace_spec.rb
This PR contains code to fix the issue where attributes are missing when they have the same name but different prefix.
Specs are also added to ensure the functionality works correctly.
closes #254
=> fix: missing attributes when elements have same name but different prefix

README.adoc, lib/lutaml/model/xml_adapter/builder/oga.rb, lib/lutaml/model/xml_adapter/builder/ox.rb, lib/lutaml/model/xml_adapter/nokogiri_adapter.rb, lib/lutaml/model/xml_adapter/oga_adapter.rb, lib/lutaml/model/xml_adapter/ox_adapter.rb, lib/lutaml/model/xml_adapter/xml_document.rb, spec/lutaml/model/mixed_content_spec.rb
This PR fixes the `UndefinedConversionError` encoding error when the `to_xml` is called using the **Ox** adapter.
An example error fixed in the PR:
```ruby
Encoding::UndefinedConversionError:
"\xC2" from ASCII-8BIT to UTF-8
```
originated in unitsml/unitsml-ruby#27
=> Fixed encoding error `UndefinedConversionError` for Ox adapter

lib/lutaml/model/schema/xml_compiler.rb, spec/fixtures/xml/address_example_260.xsd, spec/lutaml/model/schema/xml_compiler_spec.rb
This PR adds the `mixed` option for `complexType` in the **schema** to **Lutaml::Model** compilation.
closes #260
=> Content mapping for `mixed` argument

README.adoc
Added `ordered: true`, highlighting its difference from `mixed: true`.
closes #255
=> readme: added ordered: true

lib/lutaml/model/attribute.rb, lib/lutaml/model/type/decimal.rb, lib/lutaml/model/type/time.rb, lib/lutaml/model/xml_adapter/xml_document.rb, spec/ceramic_spec.rb, spec/fixtures/ceramic.rb, spec/lutaml/model/type_spec.rb
This PR fixes the issue of the overrided methods in the inherited classes from `Lutaml::Model::Type` not working.
closes #224, closes #199
=> fix: overriding classes from lutaml type not working

README.adoc
Added documentation for `mapping_hash.node`
Updated Readme for `custom model with custom methods`
closes #131
closes #141
=> added mapping_hash_node and custom_model_with_custom_methods

.rubocop_todo.yml, lib/lutaml/model/serialize.rb, spec/lutaml/model/xml_mapping_spec.rb
Fixed an issue where an element named `text` is not being parsed.
fixes #308
=> fix: XML element named text not parsing

lib/lutaml/model/attribute.rb, lib/lutaml/model/serialize.rb, spec/lutaml/model/custom_model_spec.rb
This PR fixes the behavior of the `model` function in the **Serializable** class. 
should fix plurimath/plurimath#339
=> Fix for `custom model`'s class won't initialize

lib/lutaml/model/validation.rb, spec/lutaml/model/validation_spec.rb
This PR will make validation flow consistent by not calling `validate!` inside `validate` method as explained by @ronaldtse in this [comment](https://github.com/lutaml/lutaml-model/issues/282#issuecomment-2627815943)
> I agree that this trace is weird because validate should not call validate!. Seems like a bug to me.
closes #282
=> make validation flow consistent

.rubocop_todo.yml, Gemfile, README.adoc, lib/lutaml/model/error.rb, lib/lutaml/model/error/liquid_not_enabled_error.rb, lib/lutaml/model/liquefiable.rb, lib/lutaml/model/serialize.rb, spec/lutaml/model/liquefiable_spec.rb, spec/spec_helper.rb
This PR removes the default registration of classes and methods in **Liquid**, making this functionality optional to the user.
related => plurimath/plurimath#289
=> Default to optional liquid dependency

README.adoc, lib/lutaml/model/attribute.rb, lib/lutaml/model/choice.rb, lib/lutaml/model/mapping/xml_mapping.rb, lib/lutaml/model/sequence.rb, lib/lutaml/model/serialize.rb, spec/lutaml/model/attribute_spec.rb, spec/lutaml/model/group_spec.rb
This PR updates:
1. `import_model` is now supported for `key-value` formats.
2. Missing attribute methods with the `import_model_attributes` functionality.
This PR is also related to the **Schema** generator updates.
closes #310 
closes #321 
closes #340
=> `import_model` for all supported formats

lib/lutaml/model/xml.rb, spec/lutaml/model/xml_spec.rb
This PR corrects a typo in the adapter name from "Opal" to "Oga".
=> fix: typo in adapter name from Opal to Oga

lib/lutaml/model/collection.rb, lib/lutaml/model/mapping/key_value_mapping.rb, lib/lutaml/model/mapping/key_value_mapping_rule.rb, lib/lutaml/model/serialize.rb, spec/lutaml/model/xml/root_mappings/nested_child_mappings_spec.rb
Added the missing `Collection` attributes when inherited and included the `root_mappings` in the `key_value_mapping`'s `deep_dup` method.
closes #449
=> fix: missing 'root_mappings' and Collection inheritance

lib/lutaml/model/services/logger.rb, spec/lutaml/model/logger_spec.rb
fixes #453 
Added file path and line number where the deprecated method is called.
=> fix: deprecation warnings should display line of where the deprecated method is called

spec/lutaml/model/type/integer_spec.rb
integer_spec was failing rubocop check due to rubocop version update. 1.80.1 -> 1.80.2
changed the integer_spec.rb file to pass the check.
=> fix: rubocop issues
