lutaml/lutaml-model

lib/lutaml/model/mapping_rule.rb
lib/lutaml/model/serialize.rb
lib/lutaml/model/type.rb
lib/lutaml/model/xml_adapter.rb
lib/lutaml/model/xml_adapter/nokogiri_adapter.rb
lib/lutaml/model/xml_adapter/ox_adapter.rb
lib/lutaml/model/xml_mapping.rb
spec/fixtures/person.rb
spec/lutaml/model/xml_adapter/nokogiri_adapter_spec.rb
spec/person_spec.rb

Fixing failing specs

---

lib/lutaml/model/serialize.rb
lib/lutaml/model/xml_adapter/nokogiri_adapter.rb
spec/lutaml/model/inheritance_spec.rb
spec/lutaml/model/render_nil_spec.rb
spec/lutaml/model/xml_adapter_spec.rb

Adding support for inheritance in serializable classes.

feat: add support for inheritance in serializeable class

---

lib/lutaml/model.rb
lib/lutaml/model/serialize.rb
lib/lutaml/model/toml_adapter/toml_rb_adapter.rb
lib/lutaml/model/xml_adapter.rb
lib/lutaml/model/xml_adapter/nokogiri_adapter.rb
lib/lutaml/model/xml_adapter/ox_adapter.rb
lib/lutaml/model/yaml_adapter.rb
spec/lutaml/model/custom_model_spec.rb
spec/lutaml/model/yaml_adapter_spec.rb

Added the ability to use `custom models`
closes #25

feat: using custom models

---

lib/lutaml/model.rb
lib/lutaml/model/error.rb
lib/lutaml/model/error/invalid_value_error.rb
lib/lutaml/model/serialize.rb
spec/lutaml/model_spec.rb

Allow enumerations for an attribute
closes #22

enum for attribute

---

README.adoc
lib/lutaml/model/key_value_mapping.rb
lib/lutaml/model/mapping_rule.rb
lib/lutaml/model/serialize.rb
spec/lutaml/model/serializable_spec.rb
spec/lutaml/model/with_child_mapping_spec.rb

Adding support for child mappings when defining mappings.
closes #3

feat: adding support for child mapping

---

README.adoc

Added documentation for `values` option for attributes added in PR #27 
closes #30

added `values` directive documentation

---

README.adoc
lib/lutaml/model/type.rb

Update README for delegate compare with shale

Update README for delegate compare with shale

---

lib/lutaml/model/attribute.rb
lib/lutaml/model/serialize.rb
spec/lutaml/model/attribute_spec.rb
spec/lutaml/model/xml_adapter_spec.rb

Cast values to type when assigning to attributes
fixes #79

fix: cast values when assigning

---

lib/lutaml/model/serialize.rb
spec/lutaml/model/custom_model_spec.rb

Fixed error while using Custom model after discussion with @HassanAkbar.

Undefined method for Custom model

---

lib/lutaml/model/mapping_hash.rb
lib/lutaml/model/serialize.rb
lib/lutaml/model/xml_adapter/builder/nokogiri.rb
lib/lutaml/model/xml_adapter/nokogiri_adapter.rb
lib/lutaml/model/xml_adapter/ox_adapter.rb
lib/lutaml/model/xml_adapter/xml_document.rb
lib/lutaml/model/xml_adapter/xml_element.rb
spec/lutaml/model/custom_model_spec.rb

This will fix the custom method with custom model crash with `mixed: true`.
For #117

Fix custom model with custom method

---

lib/lutaml/model/attribute.rb
spec/lutaml/model/attribute_spec.rb

added validation for attribute value type
fix #132

validate type for attribute

---

README.adoc

Add serialization type mapping from lutaml type classes.

feat: update README for serialization type mapping

---

lib/lutaml/model/serialize.rb
lib/lutaml/model/xml_adapter/builder/nokogiri.rb
lib/lutaml/model/xml_adapter/ox_adapter.rb
lib/lutaml/model/xml_adapter/xml_document.rb
spec/fixtures/xml/special_char.xml
spec/lutaml/model/custom_model_spec.rb
spec/lutaml/model/mixed_content_spec.rb
spec/lutaml/model/xml_mapping_spec.rb
spec/spec_helper.rb

This will fix the XML escape chars issue
fixes #130 
fixes #136
fixes metanorma/niso-jats#17

Fix XML Escape Char Issue

---

README.adoc
lib/lutaml/model/type/date.rb

Update README for custom types

---

.rubocop_todo.yml
README.adoc
lib/lutaml/model/mapping_hash.rb
lib/lutaml/model/serialize.rb
lib/lutaml/model/xml_adapter/builder/nokogiri.rb
lib/lutaml/model/xml_adapter/builder/ox.rb
lib/lutaml/model/xml_adapter/nokogiri_adapter.rb
lib/lutaml/model/xml_adapter/ox_adapter.rb
lib/lutaml/model/xml_adapter/xml_document.rb
lib/lutaml/model/xml_mapping.rb
lib/lutaml/model/xml_mapping_rule.rb
spec/lutaml/model/cdata_spec.rb

Added CDATA parsing for elements
resolves #116

feat: added support for parsing cdata

---

README.adoc
lib/lutaml/model/config.rb
lib/lutaml/model/serialize.rb
spec/lutaml/model/serializable_spec.rb

Add `key_value` mapping option to define same mappings for all `key_value` mappings formats
fixes #133

add key_value mapping option

---

lib/lutaml/model/serialize.rb
spec/lutaml/model/defaults_spec.rb

Default Attributes Rendering with Custom Model
fixes #192

fix: default-attr-rendering

---

lib/lutaml/model/xml_adapter/xml_document.rb
spec/lutaml/model/xml_mapping_spec.rb

Fixes issue of custom methods with `map_all`,
fixes #194

fix: custom methods with map_all

---

lib/lutaml/model/attribute.rb
lib/lutaml/model/serialize.rb

Fixes for unistsdb-ruby PR -> https://github.com/unitsml/unitsdb-ruby/pull/4

fix for unitsml db

---

README.adoc
lib/lutaml/model/mapping_rule.rb
lib/lutaml/model/serialize.rb
lib/lutaml/model/utils.rb
spec/lutaml/model/render_nil_spec.rb

This PR fixes the issues due to `lutaml-model`. 
There are some issues in the `unitsml-ruby` because of the yaml comparison, they will be fixed in -> https://github.com/unitsml/unitsdb-ruby/pull/10
fixes unitsml/unitsdb-ruby#7
fixes unitsml/unitsdb-ruby#8

fix: unitsdb issues

---

.github/workflows/dependent-tests.yml

- https://github.com/lutaml/lutaml-model/issues/246

feat: run rspec instead rake default in dependent-tests.yml

---

lib/lutaml/model.rb
lib/lutaml/model/config.rb
lib/lutaml/model/serialize.rb
lib/lutaml/model/xml_adapter/builder/oga.rb
lib/lutaml/model/xml_adapter/oga_adapter.rb
lib/lutaml/model/xml_adapter/xml_document.rb
lutaml-model.gemspec
spec/lutaml/model/mixed_content_spec.rb
spec/lutaml/model/xml_adapter/oga_adapter_spec.rb
spec/lutaml/model/xml_mapping_spec.rb

This PR moves **Oga** implementation using **Moxml**.
closes #230
related to #227

Oga support using Moxml

---

README.adoc

Added `from_xml` encoding options
closes #256

readme: added from_xml encoding options

---

lib/lutaml/model/serialize.rb
spec/lutaml/model/custom_serialization_spec.rb
spec/lutaml/model/enum_spec.rb

Resolved Enum Value Not Persisting Issue
closes #279

fix: enum_value_not_persisting_issue

---

.github/workflows/dependent-repos.json
lib/lutaml/model/serialize.rb
spec/lutaml/model/cdata_spec.rb
spec/lutaml/model/collection_spec.rb
spec/lutaml/model/custom_model_spec.rb
spec/lutaml/model/custom_serialization_spec.rb
spec/lutaml/model/multiple_mapping_spec.rb

This PR updates the expected values of custom methods.
related to lutaml/lutaml-xsd#10

fix: passing all parsed values in custom methods

---

README.adoc
docs/custom_adapters.adoc
lib/lutaml/model/json/document.rb

Added documentation for custom adapters
closes #370

chore: documentation for custom adapters

---

lib/lutaml/model/attribute.rb
lib/lutaml/model/error/polymorphic_error.rb
spec/lutaml/model/polymorphic_spec.rb

Added support for `polymorphic: true` so it accepts any subclass that inherits from the polymorphic superclass.
closes #343

Support polymorphic true option

---

spec/lutaml/model/custom_vobject_adapter_spec.rb

chore(spec): Fix typo

---

.github/workflows/dependent-tests.yml
.github/workflows/rake.yml
README.adoc
lib/lutaml/model/transform/key_value_transform.rb
spec/lutaml/model/xml/root_mappings/nested_child_mappings_spec.rb

Fix for keyed collection not working with root mappings
fixes #442

fix: nested root_mappings

---

lib/lutaml/model/collection.rb
lib/lutaml/model/mapping/mapping_rule.rb
lib/lutaml/model/serialize.rb
lib/lutaml/model/transform.rb
lib/lutaml/model/transform/key_value_transform.rb
lib/lutaml/model/transform/xml_transform.rb
lib/lutaml/model/xml/document.rb
spec/lutaml/model/custom_model_spec.rb
spec/lutaml/model/defaults_spec.rb
spec/lutaml/model/register/xml_spec.rb

This PR updates the support of the `register` argument.
closes #443 
closes #441 
closes #440

`register` argument to `__register`
